# Project settings
ARCHITECTURE=x86_64
ARCHITECTURE_FAMILY=x86_64
ARCHITECTURE_CFLAGS=-march=x86-64 -m64
BINDIR=/usr/local/bin
BUILDDIR=/home/sadko/eclipse/spike-bender/.build
DEBUG=0
ETCDIR=/etc
EXECUTABLE_EXT=
EXPORT_SYMBOLS=1
FEATURES= 
INCDIR=/usr/local/include
INSTALL_HEADERS=1
LIBDIR=/usr/local/lib
LIBRARY_EXT=.so
LIBRARY_PREFIX=lib
PKGCONFIG_EXT=.pc
PLATFORM=Linux
PREFIX=/usr/local
ROOTDIR=/home/sadko/eclipse/spike-bender
ROOT_ARTIFACT_ID=SPIKE_BENDER
PROFILE=0
SHAREDDIR=/usr/local/share
STATICLIB_EXT=.a
TEMPDIR=/tmp
TEST=1
TRACE=0
GIT=git
INSTALL=install
PKG_CONFIG=pkg-config
AS=as
AR=ar
CC=cc
CXX=g++
LD=ld
PHP=php
CFLAGS=-march=x86-64 -m64 -O2 -DLSP_TESTING -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall
CDEFS=-DLSP_INSTALL_PREFIX=\"/usr/local\"
CXXFLAGS=-march=x86-64 -m64 -O2 -DLSP_TESTING -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall
CXXDEFS=-DLSP_INSTALL_PREFIX=\"/usr/local\"
LDFLAGS= -r
EXE_FLAGS=-march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections
SO_FLAGS=-march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections -shared  -fPIC 
INCLUDE=
HOST_PKG_CONFIG=pkg-config
HOST_AS=as
HOST_AR=ar
HOST_CC=cc
HOST_CXX=g++
HOST_LD=ld
HOST_PHP=php
HOST_CFLAGS=-march=x86-64 -m64 -O2 -DLSP_TESTING -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall
HOST_CDEFS=-DLSP_INSTALL_PREFIX=\"/usr/local\"
HOST_CXXFLAGS=-march=x86-64 -m64 -O2 -DLSP_TESTING -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall
HOST_CXXDEFS=-DLSP_INSTALL_PREFIX=\"/usr/local\"
HOST_LDFLAGS= -r
HOST_EXE_FLAGS=-march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections
HOST_SO_FLAGS=-march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections -shared  -fPIC 
LSP_COMMON_LIB_NAME=lsp-common-lib
LSP_COMMON_LIB_DESC=
LSP_COMMON_LIB_VERSION=1.0.26
LSP_COMMON_LIB_TYPE=src
LSP_COMMON_LIB_URL=git@github.com:lsp-plugins/lsp-common-lib.git
LSP_COMMON_LIB_BRANCH=devel
LSP_COMMON_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib
LSP_COMMON_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/include
LSP_COMMON_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/src
LSP_COMMON_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/test
LSP_COMMON_LIB_TESTING=0
LSP_COMMON_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-common-lib
LSP_COMMON_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN
LSP_COMMON_LIB_MFLAGS=-DLSP_COMMON_LIB_BUILTIN -fvisibility=hidden
LSP_COMMON_LIB_LDFLAGS=
LSP_COMMON_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-common-lib/lsp-common-lib.o
LSP_COMMON_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-common-lib/lsp-common-lib-test.o
HOST_LSP_COMMON_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib
HOST_LSP_COMMON_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/include
HOST_LSP_COMMON_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/src
HOST_LSP_COMMON_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/test
HOST_LSP_COMMON_LIB_TESTING=0
HOST_LSP_COMMON_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-common-lib
HOST_LSP_COMMON_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN
HOST_LSP_COMMON_LIB_MFLAGS=-DLSP_COMMON_LIB_BUILTIN -fvisibility=hidden
HOST_LSP_COMMON_LIB_LDFLAGS=
HOST_LSP_COMMON_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-common-lib/lsp-common-lib.o
HOST_LSP_COMMON_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-common-lib/lsp-common-lib-test.o
LSP_LLTL_LIB_NAME=lsp-lltl-lib
LSP_LLTL_LIB_DESC=
LSP_LLTL_LIB_VERSION=1.0.9
LSP_LLTL_LIB_TYPE=src
LSP_LLTL_LIB_URL=git@github.com:lsp-plugins/lsp-lltl-lib.git
LSP_LLTL_LIB_BRANCH=devel
LSP_LLTL_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib
LSP_LLTL_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/include
LSP_LLTL_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/src
LSP_LLTL_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/test
LSP_LLTL_LIB_TESTING=0
LSP_LLTL_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-lltl-lib
LSP_LLTL_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN
LSP_LLTL_LIB_MFLAGS=-DLSP_LLTL_LIB_BUILTIN -fvisibility=hidden
LSP_LLTL_LIB_LDFLAGS=
LSP_LLTL_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-lltl-lib/lsp-lltl-lib.o
LSP_LLTL_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-lltl-lib/lsp-lltl-lib-test.o
HOST_LSP_LLTL_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib
HOST_LSP_LLTL_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/include
HOST_LSP_LLTL_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/src
HOST_LSP_LLTL_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/test
HOST_LSP_LLTL_LIB_TESTING=0
HOST_LSP_LLTL_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-lltl-lib
HOST_LSP_LLTL_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN
HOST_LSP_LLTL_LIB_MFLAGS=-DLSP_LLTL_LIB_BUILTIN -fvisibility=hidden
HOST_LSP_LLTL_LIB_LDFLAGS=
HOST_LSP_LLTL_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-lltl-lib/lsp-lltl-lib.o
HOST_LSP_LLTL_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-lltl-lib/lsp-lltl-lib-test.o
LSP_RUNTIME_LIB_NAME=lsp-runtime-lib
LSP_RUNTIME_LIB_DESC=
LSP_RUNTIME_LIB_VERSION=1.0.12
LSP_RUNTIME_LIB_TYPE=src
LSP_RUNTIME_LIB_URL=git@github.com:lsp-plugins/lsp-runtime-lib.git
LSP_RUNTIME_LIB_BRANCH=devel
LSP_RUNTIME_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib
LSP_RUNTIME_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/include
LSP_RUNTIME_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/src
LSP_RUNTIME_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/test
LSP_RUNTIME_LIB_TESTING=0
LSP_RUNTIME_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-runtime-lib
LSP_RUNTIME_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN
LSP_RUNTIME_LIB_MFLAGS=-DLSP_RUNTIME_LIB_BUILTIN -fvisibility=hidden
LSP_RUNTIME_LIB_LDFLAGS=
LSP_RUNTIME_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-runtime-lib/lsp-runtime-lib.o
LSP_RUNTIME_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-runtime-lib/lsp-runtime-lib-test.o
HOST_LSP_RUNTIME_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib
HOST_LSP_RUNTIME_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/include
HOST_LSP_RUNTIME_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/src
HOST_LSP_RUNTIME_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/test
HOST_LSP_RUNTIME_LIB_TESTING=0
HOST_LSP_RUNTIME_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-runtime-lib
HOST_LSP_RUNTIME_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN
HOST_LSP_RUNTIME_LIB_MFLAGS=-DLSP_RUNTIME_LIB_BUILTIN -fvisibility=hidden
HOST_LSP_RUNTIME_LIB_LDFLAGS=
HOST_LSP_RUNTIME_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-runtime-lib/lsp-runtime-lib.o
HOST_LSP_RUNTIME_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-runtime-lib/lsp-runtime-lib-test.o
LSP_DSP_LIB_NAME=lsp-dsp-lib
LSP_DSP_LIB_DESC=
LSP_DSP_LIB_VERSION=1.0.10
LSP_DSP_LIB_TYPE=src
LSP_DSP_LIB_URL=git@github.com:lsp-plugins/lsp-dsp-lib.git
LSP_DSP_LIB_BRANCH=devel
LSP_DSP_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib
LSP_DSP_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/include
LSP_DSP_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/src
LSP_DSP_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/test
LSP_DSP_LIB_TESTING=0
LSP_DSP_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-lib
LSP_DSP_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN
LSP_DSP_LIB_MFLAGS=-DLSP_DSP_LIB_BUILTIN -fvisibility=hidden
LSP_DSP_LIB_LDFLAGS=
LSP_DSP_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-lib/lsp-dsp-lib.o
LSP_DSP_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-lib/lsp-dsp-lib-test.o
HOST_LSP_DSP_LIB_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib
HOST_LSP_DSP_LIB_INC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/include
HOST_LSP_DSP_LIB_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/src
HOST_LSP_DSP_LIB_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/test
HOST_LSP_DSP_LIB_TESTING=0
HOST_LSP_DSP_LIB_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-lib
HOST_LSP_DSP_LIB_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN
HOST_LSP_DSP_LIB_MFLAGS=-DLSP_DSP_LIB_BUILTIN -fvisibility=hidden
HOST_LSP_DSP_LIB_LDFLAGS=
HOST_LSP_DSP_LIB_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-lib/lsp-dsp-lib.o
HOST_LSP_DSP_LIB_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-lib/lsp-dsp-lib-test.o
LSP_DSP_UNITS_NAME=lsp-dsp-units
LSP_DSP_UNITS_DESC=
LSP_DSP_UNITS_VERSION=1.0.9
LSP_DSP_UNITS_TYPE=src
LSP_DSP_UNITS_URL=git@github.com:lsp-plugins/lsp-dsp-units.git
LSP_DSP_UNITS_BRANCH=devel
LSP_DSP_UNITS_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units
LSP_DSP_UNITS_INC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/include
LSP_DSP_UNITS_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/src
LSP_DSP_UNITS_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/test
LSP_DSP_UNITS_TESTING=0
LSP_DSP_UNITS_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-units
LSP_DSP_UNITS_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/include" -DLSP_DSP_UNITS_BUILTIN
LSP_DSP_UNITS_MFLAGS=-DLSP_DSP_UNITS_BUILTIN -fvisibility=hidden
LSP_DSP_UNITS_LDFLAGS=
LSP_DSP_UNITS_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-units/lsp-dsp-units.o
LSP_DSP_UNITS_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-dsp-units/lsp-dsp-units-test.o
HOST_LSP_DSP_UNITS_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units
HOST_LSP_DSP_UNITS_INC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/include
HOST_LSP_DSP_UNITS_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/src
HOST_LSP_DSP_UNITS_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/test
HOST_LSP_DSP_UNITS_TESTING=0
HOST_LSP_DSP_UNITS_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-units
HOST_LSP_DSP_UNITS_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-dsp-units/include" -DLSP_DSP_UNITS_BUILTIN
HOST_LSP_DSP_UNITS_MFLAGS=-DLSP_DSP_UNITS_BUILTIN -fvisibility=hidden
HOST_LSP_DSP_UNITS_LDFLAGS=
HOST_LSP_DSP_UNITS_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-units/lsp-dsp-units.o
HOST_LSP_DSP_UNITS_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-dsp-units/lsp-dsp-units-test.o
LIBPTHREAD_NAME=libpthread
LIBPTHREAD_DESC=
LIBPTHREAD_VERSION=system
LIBPTHREAD_TYPE=opt
LIBPTHREAD_URL=
LIBPTHREAD_BRANCH=devel
LIBPTHREAD_PATH=
LIBPTHREAD_INC=
LIBPTHREAD_SRC=
LIBPTHREAD_TEST=
LIBPTHREAD_TESTING=
LIBPTHREAD_BIN=
LIBPTHREAD_CFLAGS=
LIBPTHREAD_MFLAGS=
LIBPTHREAD_LDFLAGS=-lpthread
LIBPTHREAD_OBJ=
LIBPTHREAD_OBJ_TEST=
HOST_LIBPTHREAD_PATH=
HOST_LIBPTHREAD_INC=
HOST_LIBPTHREAD_SRC=
HOST_LIBPTHREAD_TEST=
HOST_LIBPTHREAD_TESTING=
HOST_LIBPTHREAD_BIN=
HOST_LIBPTHREAD_CFLAGS=
HOST_LIBPTHREAD_MFLAGS=
HOST_LIBPTHREAD_LDFLAGS=-lpthread
HOST_LIBPTHREAD_OBJ=
HOST_LIBPTHREAD_OBJ_TEST=
LIBDL_NAME=libdl
LIBDL_DESC=
LIBDL_VERSION=system
LIBDL_TYPE=opt
LIBDL_URL=
LIBDL_BRANCH=devel
LIBDL_PATH=
LIBDL_INC=
LIBDL_SRC=
LIBDL_TEST=
LIBDL_TESTING=
LIBDL_BIN=
LIBDL_CFLAGS=
LIBDL_MFLAGS=
LIBDL_LDFLAGS=-ldl
LIBDL_OBJ=
LIBDL_OBJ_TEST=
HOST_LIBDL_PATH=
HOST_LIBDL_INC=
HOST_LIBDL_SRC=
HOST_LIBDL_TEST=
HOST_LIBDL_TESTING=
HOST_LIBDL_BIN=
HOST_LIBDL_CFLAGS=
HOST_LIBDL_MFLAGS=
HOST_LIBDL_LDFLAGS=-ldl
HOST_LIBDL_OBJ=
HOST_LIBDL_OBJ_TEST=
LIBSNDFILE_NAME=sndfile
LIBSNDFILE_DESC=
LIBSNDFILE_VERSION=system
LIBSNDFILE_TYPE=pkg
LIBSNDFILE_URL=
LIBSNDFILE_BRANCH=devel
LIBSNDFILE_PATH=
LIBSNDFILE_INC=
LIBSNDFILE_SRC=
LIBSNDFILE_TEST=
LIBSNDFILE_TESTING=
LIBSNDFILE_BIN=
LIBSNDFILE_CFLAGS=
LIBSNDFILE_MFLAGS=
LIBSNDFILE_LDFLAGS=-lsndfile
LIBSNDFILE_OBJ=
LIBSNDFILE_OBJ_TEST=
HOST_LIBSNDFILE_PATH=
HOST_LIBSNDFILE_INC=
HOST_LIBSNDFILE_SRC=
HOST_LIBSNDFILE_TEST=
HOST_LIBSNDFILE_TESTING=
HOST_LIBSNDFILE_BIN=
HOST_LIBSNDFILE_CFLAGS=
HOST_LIBSNDFILE_MFLAGS=
HOST_LIBSNDFILE_LDFLAGS=-lsndfile
HOST_LIBSNDFILE_OBJ=
HOST_LIBSNDFILE_OBJ_TEST=
LSP_TEST_FW_NAME=lsp-test-fw
LSP_TEST_FW_DESC=
LSP_TEST_FW_VERSION=1.0.19
LSP_TEST_FW_TYPE=src
LSP_TEST_FW_URL=git@github.com:lsp-plugins/lsp-test-fw.git
LSP_TEST_FW_BRANCH=devel
LSP_TEST_FW_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw
LSP_TEST_FW_INC=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/include
LSP_TEST_FW_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/src
LSP_TEST_FW_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/test
LSP_TEST_FW_TESTING=0
LSP_TEST_FW_BIN=/home/sadko/eclipse/spike-bender/.build/target/lsp-test-fw
LSP_TEST_FW_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/include" -DLSP_TEST_FW_BUILTIN
LSP_TEST_FW_MFLAGS=-DLSP_TEST_FW_BUILTIN -fvisibility=hidden
LSP_TEST_FW_LDFLAGS=
LSP_TEST_FW_OBJ=/home/sadko/eclipse/spike-bender/.build/target/lsp-test-fw/lsp-test-fw.o
LSP_TEST_FW_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/lsp-test-fw/lsp-test-fw-test.o
HOST_LSP_TEST_FW_PATH=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw
HOST_LSP_TEST_FW_INC=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/include
HOST_LSP_TEST_FW_SRC=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/src
HOST_LSP_TEST_FW_TEST=/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/test
HOST_LSP_TEST_FW_TESTING=0
HOST_LSP_TEST_FW_BIN=/home/sadko/eclipse/spike-bender/.build/host/lsp-test-fw
HOST_LSP_TEST_FW_CFLAGS=-I"/home/sadko/eclipse/spike-bender/modules/lsp-test-fw/include" -DLSP_TEST_FW_BUILTIN
HOST_LSP_TEST_FW_MFLAGS=-DLSP_TEST_FW_BUILTIN -fvisibility=hidden
HOST_LSP_TEST_FW_LDFLAGS=
HOST_LSP_TEST_FW_OBJ=/home/sadko/eclipse/spike-bender/.build/host/lsp-test-fw/lsp-test-fw.o
HOST_LSP_TEST_FW_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/lsp-test-fw/lsp-test-fw-test.o
SPIKE_BENDER_NAME=spike-bender
SPIKE_BENDER_DESC=Spike Bender - a tool for dynamics correction
SPIKE_BENDER_VERSION=0.1.0
SPIKE_BENDER_TYPE=src
SPIKE_BENDER_URL=
SPIKE_BENDER_BRANCH=
SPIKE_BENDER_PATH=/home/sadko/eclipse/spike-bender
SPIKE_BENDER_INC=/home/sadko/eclipse/spike-bender/include
SPIKE_BENDER_SRC=/home/sadko/eclipse/spike-bender/src
SPIKE_BENDER_TEST=/home/sadko/eclipse/spike-bender/test
SPIKE_BENDER_TESTING=1
SPIKE_BENDER_BIN=/home/sadko/eclipse/spike-bender/.build/target/spike-bender
SPIKE_BENDER_CFLAGS=-I"/home/sadko/eclipse/spike-bender/include" -DSPIKE_BENDER_BUILTIN -DSPIKE_BENDER_PUBLISHER
SPIKE_BENDER_MFLAGS=
SPIKE_BENDER_LDFLAGS=
SPIKE_BENDER_OBJ=/home/sadko/eclipse/spike-bender/.build/target/spike-bender/spike-bender.o
SPIKE_BENDER_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/target/spike-bender/spike-bender-test.o
HOST_SPIKE_BENDER_PATH=/home/sadko/eclipse/spike-bender
HOST_SPIKE_BENDER_INC=/home/sadko/eclipse/spike-bender/include
HOST_SPIKE_BENDER_SRC=/home/sadko/eclipse/spike-bender/src
HOST_SPIKE_BENDER_TEST=/home/sadko/eclipse/spike-bender/test
HOST_SPIKE_BENDER_TESTING=0
HOST_SPIKE_BENDER_BIN=/home/sadko/eclipse/spike-bender/.build/host/spike-bender
HOST_SPIKE_BENDER_CFLAGS=-I"/home/sadko/eclipse/spike-bender/include" -DSPIKE_BENDER_BUILTIN -DSPIKE_BENDER_PUBLISHER
HOST_SPIKE_BENDER_MFLAGS=
HOST_SPIKE_BENDER_LDFLAGS=
HOST_SPIKE_BENDER_OBJ=/home/sadko/eclipse/spike-bender/.build/host/spike-bender/spike-bender.o
HOST_SPIKE_BENDER_OBJ_TEST=/home/sadko/eclipse/spike-bender/.build/host/spike-bender/spike-bender-test.o
